### ISSUE TITLE
Choose assertion library

### ISSUE THREAD

**Issue by lithgow** [xp-dojo/atdd-bank-account#11]
Let's pick one (hamcrest/assertj) and make it consistent. They both seem pretty readable to me so I can't see a compelling reason to have both in there (and I don't mind which we settle on).

**Comment by tobyweston** [comment]
ah man! I don't think I can be objective here. I have a soft spot for hamcrest but can't really evaluate aspectj against it in terms of features. 

The only thing I care about is readable failures and I've gotten used to `Matchers` being very expressive (i.e dont just fail but explain nicely why). I suspect we won't see the difference in this code base as it's so simple, but with something where sophisticated matchers come into play, it may be more apparent... maybe if we did a `StatementMatcher`?

You right to point it out though :weary:
