### ISSUE TITLE
Get Travis cooking

### ISSUE THREAD

**Issue by tobyweston** [xp-dojo/atdd-bank-account#12]
At the risk of too much WIP, I thought it would be straight forward but https://travis-ci.com/xp-dojo/atdd-bank-account/jobs/183692865 says otherwise.

Now all I can think about is getting this green.

![](https://cdn-images-1.medium.com/max/1600/1*nR8Gow0ukWXWZdkofgkT8A.png)

**Comment by tobyweston** [comment]
groan, I just realised, I set this up on https://travis-ci.com/ and not https://travis-ci.org ffs

consider it a spike and we'll unwind and start again

**Comment by tobyweston** [comment]
Switched to .org https://travis-ci.org/xp-dojo/atdd-bank-account/builds/504837457 revert https://github.com/xp-dojo/atdd-bank-account/commit/a7aaee99353a080f359dedaf005c109057afee15 if you want to have another go

**Comment by suggitpe** [comment]
I have committed a travis cfg that works for my gradle build on another project if thats helpful.

**Comment by suggitpe** [comment]
@tobyweston to review and close ... seems to work now ...

**Comment by tobyweston** [comment]
I wonder if #15 was the cause when we couldn't get it working before. From the previous (failed) attempt:

```
org.xpdojo.bank.ViewBalanceSlipPrintoutFixture > initializationError FAILED
    java.lang.RuntimeException
        Caused by: java.io.FileNotFoundException
org.xpdojo.bank.ViewBalanceSlipForUninitialisedAccountFixture > initializationError FAILED
    java.lang.RuntimeException
        Caused by: java.io.FileNotFoundException
org.xpdojo.bank.ViewBalanceSlipFixture > initializationError FAILED
    java.lang.RuntimeException
        Caused by: java.io.FileNotFoundException
```

**Comment by tobyweston** [comment]
Perhaps get this working for the instructor branch also?

**Comment by suggitpe** [comment]
all working on both branches now ... configured to run on all branches now

**Comment by suggitpe** [comment]
Travis configured to run a build on master / instructors if there have been no commits for 24 hrs ... stops it going stale ...
