### ISSUE TITLE
ConcordionResource fails with FileNotFound over concordion.css

### ISSUE THREAD

**Issue by tobyweston** [xp-dojo/atdd-bank-account#15]
See https://stackoverflow.com/questions/55250429/concordion-can-not-copy-resource-all-of-a-sudden 

Concordion will try and create a file which if it contains relative paths, can fail with file not found errors. 

For example:

```bash
ll /var/folders/wg/3nnv2yf90914pqpx69wmd9cc0000gn/T/concordion/org/xpdojo/bank/../../../concordion.css (No such file or directory
```
because only `concordion` above exists, it hasn't gotten around to creating the `org/xpdojo/bank` bit yet, so will fail.

Reproducible on Mac and Linux by deleting the temp folder.

**Comment by tobyweston** [comment]
@suggitpe to verify and close 😃

**Comment by suggitpe** [comment]
I cannot reproduce the issue anymore.
