### ISSUE TITLE
Maven/Gradle/No-deps

### ISSUE THREAD

**Issue by tobyweston** [xp-dojo/atdd-bank-account#3]
Merging the concordion branch has raised a few questions.

I don't think the project works out of the box as is, I couldn't open in IDEA from a clean clone. Was`git rm --cached` run on the bits to remove - was stuff removed at all? I'm a bit confused on it.

Anyway, the Concordion stuff, I brought in with Gradle and Maven support 😱 and now aren't sure what to do in the interest of gettings things cooking.

I may update the POM and build.gradle (for now) so its belts and braces, but let's use this issue to track our thoughts. Spoke to Suggs the other day who is 👨🐜(adam-ant) on gradle support...

**Comment by tobyweston** [comment]
What JDK were you using to compile things?  I get

```
Error:java: javacTask: source release 8 requires target release 1.8
```

**Comment by lithgow** [comment]
I was using java 8

I think gradle may make sense to get things running out of the box, otherwise there's a bit too much manual setup in IntelliJ (setting the dirs, etc)
