### ISSUE TITLE
General test feedback for first iteration

### ISSUE THREAD

**Issue by tobyweston** [xp-dojo/atdd-bank-account#4]
Not really sure about some of the annotations from J5. `@DisplayName` and `@Nested`. Personally, I think it's a bit twee and shy away from annotations generally but realise it's subjective. For the pedagogical, I don't think it adds anything and may be distracting. 

It's hard to make a call because if the audience is happy with the syntax, it'll feel natural but for noobs, it'll feel scary. My default when put in this position, is to simplify.

**Comment by tobyweston** [comment]
Where's the `MoneyTest`? 😉 

But serious point: I usually make a point of "switching gears" when we "discover" money as a type and build out behaviour test first (even a basic equals test... and `toString`). Showing how we switch contexts out of "Account" into "Money" back into "Account". 

Upshot is that I think it's important to show the journey.

**Comment by tobyweston** [comment]
I think we should cut back on some Jars too. For example, 

 * `hamcrest` vs `assertj`? i.e vanilla junit + matchers doesn't require an additional jar
 * Remove all mocking or leave in in case we get creative in a demo?
 * what's `opentest4j` and `apiguardian`? suspect same motivation as point 2?

**Comment by lithgow** [comment]
Yeah, I thought I'd try out some of the JUnit5 features but I'm not convinced either as the nested stuff kind of gets in the way and makes it harder to just read the tests. For the purposes of the kata I think we can just simplify. (The reason for the ```@DisplayName``` was to support readability in the nested test name output and give it more of a spec style.)

Happy to get rid of jars too - I was following the example of the existing one but I'd rather be a little opinionated and err on the side of minimalism. I do like assertj though as it's a bit more readable (I hadn't used it before the kata).

```opentest4j``` and ```apiguardian``` are required by JUnit5. If we use gradle/maven then we can specify a single JUnit5 dependency and it'll bring in all the transitive dependencies. JUnit5 is quite modular in design, hence I had to include all the other JUnit jars too.

**Comment by lithgow** [comment]
Re: the tests, I had to leave you some of the fun ;)

It's an interesting one, as I was planning to add those tests next, adding some for decimals too (proving that we can work with decimals and also enforcing a constraint of 2dp). The intention being to keep the ```Account``` tests simple to reason about, without having to care about decimals.

I get your point though about switching gears into the ```MoneyTest``` at the points where we define plus/minus/isLessThan... I was just too eager to get the first commit in between conference days! *[smacks hand]*

**Comment by lithgow** [comment]
Just seen you've already added gradle, so I'd say let's ditch all of the checked in jars now. (IntelliJ can sometimes be a little slow to recognise new dependencies (i.e. when you added concordion) but I'd be surprised if it was a persistent issue.)

Re: mocks, if attendees want to use mocks during the kata then it's trivial for them to add the dependency of their choice (or if we find we resort to them soon enough when practicing it ourselves we can always add them then.)

**Comment by tobyweston** [comment]
Closing as we're about done / moved discussions elsewhere. Feel free to reopen if it's helpful.
