### ISSUE TITLE
Test folder structure tweaks

### ISSUE THREAD

**Issue by tobyweston** [xp-dojo/atdd-bank-account#6]
I propose we structure the test packages something like the following:

```
src
 ├───test
 │       ├───unit
 │       │       ├───java
 │       │       └───resources
 │       └───acceptance
 │               ├───java
 │               └───resources
 └─── ...
```
The point being to make it clearer for attendees what's an acceptance test and what's a "unit"-style test.

Trouble I'll have is setting up Gradle :cry:

**Comment by lithgow** [comment]
Yeah, maven might actually give you more trouble as gradle *should* be pretty easy to reconfigure. We'd just need to tweak the `src` and `resource` dirs of the standard `test` task and configure another task called `acceptance-test`, with source structures under `src/test/acceptance`, then wire that into the task dependencies.

I've done this sort of stuff before if you want me to take a look (I might even have done it on the previous project at work so can take a look at that for reference). A quick google yields this example to give you a clearer idea:

https://www.petrikainulainen.net/programming/gradle/getting-started-with-gradle-integration-testing/

**Comment by lithgow** [comment]
Now we've merged the new structure with gradle, I'm not sure what to do with maven, as it doesn't pick up the structure or run any of the tests. Unless we can find a relatively quick way to get it working, my vote would be to abandon it and stick purely to gradle for now, then we can close this issue.

**Comment by tobyweston** [comment]
I think kill the `pom.xml`.

**Comment by lithgow** [comment]
Gets my vote! I'll kill it in my current branch and close this issue.
